### ISSUE TITLE
Proposal creator must be a voter

### ISSUE THREAD

**Issue by jac18281828** [collectivexyz/collective-governance-v1#45]
Requirement to prevent spam

* spam is already highly limited to 1 proposal per VOTE_DURATION

**Comment by rocketman-21** [comment]
people can still spin up a ton of wallets and spam right?

**Comment by rocketman-21** [comment]
here's some more context:

https://houseofnouns.wtf/proposals/159

check vote reasons!

some more context:
https://houseofnouns.wtf/proposals/5
https://houseofnouns.wtf/proposals/134

**Comment by rocketman-21** [comment]
<img width="1010" alt="Screen Shot 2022-12-15 at 5 16 04 PM" src="https://user-images.githubusercontent.com/20303031/207978877-43305315-e3e5-4e20-ae02-f946642d0d71.png">

not necessary for MVP but also an interesting way to balance both spam + prop velocity/accessibility imo

[what Compound has](https://medium.com/compound-finance/compound-autonomous-proposals-354e7a2ad6b7).

imagine having an ideas board that the community automatically votes the best ideas through to proposal? many nouners do this already on Twitter eg: post what you want proposed and I'll sponsor you.
