### ISSUE TITLE
time maximums

### ISSUE THREAD

**Issue by jac18281828** [collectivexyz/collective-governance-v1#47]
Allow the community to set optional maximum voting durations.   This can be used to prevent invalid votes and also in concert with minimum to establish only a single allowed voting time for a comunity.

**Comment by rocketman-21** [comment]
Nouns approaches this by having a voting delay and voting period which are set to 5 and 2 days, so total there is 7 days that the community has to decide on a prop

https://houseofnouns.wtf/proposals/161
