### ISSUE TITLE
startVote and endVote may be called by anyone

### ISSUE THREAD

**Issue by jac18281828** [collectivexyz/collective-governance-v1#50]
remove the supervisor requirement from startVote and endVote.   If the endVote executions have requirements it will be up to them to enforce it.

**Comment by jac18281828** [comment]
Added question as the endVote may require some testing with various accounts to verify this can work.

**Comment by rocketman-21** [comment]
wdym by endVote executions?

**Comment by rocketmanh** [comment]
add timelock

**Comment by rocketman-21** [comment]
the fact that anyone can execute queued Nouns proposals (ones that have passed) is a great feature and makes it so the community doesn’t have to trust any one party/person to take action imo
